Repository eternialz/moeverdose, pull requests merged in 2019-07, with the labels that each got.

#28 Add design in devise mails
  config/initializers/devise.rb
  frontend/components/shared/main-menu/_main-menu.erb
  frontend/stylesheets/components/_main-menu.scss
  frontend/stylesheets/components/_user-show.scss
  frontend/views/devise/mailer/confirmation_instructions.html.erb
  frontend/views/devise/mailer/password_change.html.erb
  frontend/views/devise/mailer/reset_password_instructions.html.erb
  frontend/views/devise/mailer/shared/_header.html.erb
  frontend/views/devise/mailer/unlock_instructions.html.erb
Labels: Enhancement

#35 Fixes/editable author
  app/controllers/authors_controller.rb
  app/controllers/tags_controller.rb
  app/models/author.rb
  app/models/tag.rb
  frontend/components/authors/edit/_edit.erb
Labels: Bug, Enhancement

#36 feat(gdpr): Added possibility to extract all user's infos from moeverdose
  .gitignore
  .ruby-version
  .snyk
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/users_controller.rb
  app/logics/user_logic.rb
  app/models/application_record.rb
  app/models/user.rb
  app/services/post_service.rb
  app/services/raw_sql_service.rb
  app/services/tag_service.rb
  app/services/twitter_bot.rb
  app/services/user_service.rb
  app/services/zip_service.rb
  config/application.rb
  config/routes.rb
  frontend/components/users/edit/_edit.erb
  package.json
  test/factory_helpers.rb
  test/file_helper.rb
  test/services/user_service_test.rb
  test/test_helper.rb
  yarn.lock
Labels: Enhancement, Theme:Legal, Theme:User
